language: java

jdk:
 - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
 - chmod +x gradlew
 - export DISPLAY=:99.0
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

after_success:
 - ./gradlew jacocoTestReport coveralls

after_failure:
 - "cat /home/travis/build/gemcfadyen/Apprenticeship-JavaTicTacToe/build/reports/tests/index.html"
